name: Lint Code Base

on:
  push:
    branches: [master, develop, "release/**", sandbox/**]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Linting the Code Base
    runs-on: linux-dind

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python(3.9)
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Add ruff problem matcher
      run: echo "::add-matcher::.github/flake8-problem-matcher.json"

    - name: Lint with ruff
      run: |
        ruff check . --output-format=full
