"""File used to store all constants used in kpis from MF directory"""


class CycleTimeConstants:
    """Defining the constants for Cycle Time"""

    VEDODO_CYCLE_TIME_MS = 10
    TCE_CYCLE_TIME_MS = 10
    TRJCTL_CYCLE_TIME_MS = 10
    US_CYCLE_TIME_MS = 33
    ISP_CYCLE_TIME_MS = 33
    OFC_CYCLE_TIME_MS = 66
    SYNC_CYCLE_TIME_MS = 66
    CHIPS_CYLINDRICAL_PROCESSING_CYCLE_TIME_MS = 133
    CHIPS_PYRAMID_PROCESSING_CYCLE_TIME_MS = 66
    OFT_CYCLE_TIME_MS = 66
    GDR_CYCLE_TIME_MS = 66
    EMO_CYCLE_TIME_MS = 66
    GRAPPA_CYCLE_TIME_MS = 133
    SPP_CYCLE_TIME_MS = 133
    PMSD_CYCLE_TIME_MS = 133
    TPP_CYCLE_TIME_MS = 133
    CEM_LSM_CYCLE_TIME_MS = 33
    SI_CYCLE_TIME_MS = 33
    LSCA_CYCLE_TIME_MS = 33
    PDW_CYCLE_TIME_MS = 33
    TRAJPLA_CYCLE_TIME_MS = 33
    PARKSM_CYCLE_TIME_MS = 33
    APPDEMO_PARKSM_CYCLE_TIME_MS = 33
    VISU_CYCLE_TIME_MS = 33
    MF_MANAGER_TIME_MS = 33
    WHLPROTECTPROC_TIME_MS = 33
    APPDEMO_DEVWAENSM_TIME_MS = 33
    MF_DRVWAENSM_TIME_MS = 33
    APPDEMO_TONH_CYCLE_TIME_MS = 33
    APPDEMO_HMIH_CYCLE_TIME_MS = 33


class ThresholdTimeConstants:
    """Defining the constants for Threshold Time"""

    THRESHOLD = 2.5
